# Generated by Django 2.2.1 on 2019-05-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookinshop',
            constraint=models.UniqueConstraint(fields=('book', 'shop'), name='one_book_per_shop'),
        ),
    ]
